load("@gazelle//:def.bzl", "gazelle")
load("@rules_go//go:def.bzl", "go_library", "go_test")

# gazelle:prefix github.com/sentioxyz/arbiter-core
# gazelle:resolve go github.com/housegate/housegate/pkg/lthash @housegate//pkg/lthash
# gazelle:resolve go github.com/housegate/housegate/pkg/replay @housegate//pkg/replay
# gazelle:resolve go github.com/housegate/housegate/pkg/replay/chexec @housegate//pkg/replay/chexec
# gazelle:resolve go github.com/housegate/housegate/pkg/replay/nativepayload @housegate//pkg/replay/nativepayload
# gazelle:resolve go github.com/housegate/housegate/pkg/replay/payloadexec @housegate//pkg/replay/payloadexec
# gazelle:resolve go github.com/housegate/housegate/pkg/auth @housegate//pkg/auth

gazelle(name = "gazelle")

go_library(
    name = "arbiter-core",
    srcs = [
        "domains.go",
        "types.go",
    ],
    importpath = "github.com/sentioxyz/arbiter-core",
    visibility = ["//visibility:public"],
)

go_test(
    name = "arbiter-core_test",
    srcs = ["types_test.go"],
    embed = [":arbiter-core"],
)
