load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "authoritytest",
    srcs = [
        "fixtures.go",
        "vectors.go",
    ],
    importpath = "github.com/sentioxyz/arbiter-core/authority/authoritytest",
    visibility = ["//visibility:public"],
    deps = [
        "//:arbiter-core",
        "//authority",
    ],
)

go_test(
    name = "authoritytest_test",
    srcs = ["vectors_test.go"],
    deps = [
        ":authoritytest",
        "//authority",
    ],
)
