load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "authority",
    srcs = [
        "payload.go",
        "signer.go",
        "validator.go",
    ],
    importpath = "github.com/sentioxyz/arbiter-core/authority",
    visibility = ["//visibility:public"],
    deps = [
        "//:arbiter-core",
        "@com_github_ethereum_go_ethereum//crypto",
        "@housegate//pkg/replay",
    ],
)

go_test(
    name = "authority_test",
    srcs = ["authority_test.go"],
    embed = [":authority"],
    deps = ["//:arbiter-core"],
)
